version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
