# Dockerfile.fastapi
FROM python:3.9-slim

# Installer les dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copier le code de l'application
COPY . /app
WORKDIR /app

# Exposer le port utilisé par FastAPI
EXPOSE 8000

# Lancer l'application FastAPI
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
